import base64
import hashlib
import io
import json
import os
import re
import threading
from concurrent.futures import ThreadPoolExecutor
from collections import OrderedDict
from dataclasses import dataclass
from typing import Optional

import gradio as gr
import requests
from PIL import Image

from modules import scripts
from modules.processing import StableDiffusionProcessing

CACHE_SIZE = 50
VISION_CACHE = [OrderedDict() for _ in range(3)]  # one OrderedDict per slot
VISION_CACHE_LOCKS = [threading.Lock() for _ in range(3)]
IMAGES_PER_SLOT = 3

# Slot layout offsets for parsing args tuple
SLOT_STRIDE = 1 + 1 + IMAGES_PER_SLOT * 1 + 2
SLOT_ENABLED_OFF = 0
MULTI_MODE_OFF = 1
IMG_OFF = 2
SYSTEM_PROMPT_OFF = 2 + IMAGES_PER_SLOT * 1
WEIGHT_OFF = 2 + IMAGES_PER_SLOT * 1 + 1

# Response style mapping (temperature, top_p)
STYLE_MAP = {
    "strict": (0.2, 0.2),
    "balanced": (0.7, 0.9),
    "creative": (1.2, 1.0),
}

# Merge multicall prompts
MERGE_SYSTEM_TEMPLATE = (
    "You are a formatting assistant. "
    "The user will provide descriptions of multiple images (Input 1, Input 2, etc.), each generated by the same system prompt. "
    "Unless otherwise specified, your task is to combine them into a single cohesive output. "
    "Prioritize the instructions in the original system prompt below.\n\n"
    "CRITICAL: If the original system prompt uses numbered labels (e.g., <Character_1>, <Character_2>, [Subject 1], [Subject 2], Figure 1/2/3, etc.), "
    "you MUST renumber them so that Input 1 becomes the first label (1), Input 2 becomes the second label (2), and so on. "
    "Do NOT keep every input labeled as 1.\n\n"
    "Preserve all descriptive detail and wording as closely as possible.\n\n"
    "The system prompt used for the individual image descriptions was:\n{system_prompt}"
)

MERGE_USER_TEMPLATE = "Process the following {count} outputs:\n\n{descriptions_block}"


@dataclass
class APIParams:
    """Shared API configuration passed through the call stack."""
    model_name: str
    api_url: str
    api_key: str
    response_style: str  # "strict", "balanced", "creative"
    enable_reasoning: bool
    timeout_seconds: int

    def payload(self, system_prompt: str, user_content) -> dict:
        """Returns the shared payload attributes for vision and text calls."""
        temperature, top_p = STYLE_MAP.get(self.response_style, (0.5, 1.0))

        p = {
            "model": self.model_name,
            "temperature": temperature,
            "top_p": top_p,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_content},
            ],
        }

        if self.enable_reasoning:
            p["reasoning_effort"] = "medium"
            p["thinking_budget_tokens"] = 4096
            p["reasoning"] = {"effort": "medium"}
        else:
            p["reasoning_effort"] = "none"
            p["thinking_budget_tokens"] = 0
            p["reasoning"] = {"effort": "off"}

        return p

    def headers(self) -> dict:
        h = {"Content-Type": "application/json"}
        if self.api_key and self.api_key.strip():
            h["Authorization"] = f"Bearer {self.api_key.strip()}"
        return h

def _get_preset_path() -> str:
    """Returns the path to the presets.json file."""
    base_dir = os.path.dirname(os.path.abspath(__file__))
    return os.path.join(base_dir, "..", "presets.json")


def load_presets() -> dict:
    """Load presets from the presets.json file."""
    try:
        with open(_get_preset_path(), "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        print(f"[Vision Prompt] Failed to load presets: {e}")
        return {"Custom": ""}


SYSTEM_PROMPT_PRESETS = load_presets()


def _write_presets() -> None:
    """Write current presets to the presets.json file."""
    with open(_get_preset_path(), "w", encoding="utf-8") as f:
        json.dump(SYSTEM_PROMPT_PRESETS, f, indent=2, ensure_ascii=False)

def save_preset(name: str, prompt: str) -> tuple[gr.Dropdown, str]:
    """Save a new preset with the given name and prompt."""
    if not name.strip():
        raise Exception("[Vision Prompt] Preset name cannot be empty.")
    SYSTEM_PROMPT_PRESETS[name.strip()] = prompt
    _write_presets()
    choices = list(SYSTEM_PROMPT_PRESETS.keys())
    return gr.update(choices=choices, value=name.strip()), name.strip()


def delete_preset(name: str) -> tuple[gr.Dropdown, str]:
    """Delete a preset by name. Cannot delete the 'Custom' preset."""
    if name == "Custom":
        raise Exception("[Vision Prompt] Cannot delete the Custom preset.")
    SYSTEM_PROMPT_PRESETS.pop(name, None)
    _write_presets()
    choices = list(SYSTEM_PROMPT_PRESETS.keys())
    return gr.update(choices=choices, value="Custom"), "Custom"

def stitch_images_horizontal(images: list[Image.Image], gap: int = 0) -> Image.Image:
    """
    Stitch a list of PIL images side-by-side with an optional gap between them.
    All images are resized to the same height (the tallest one) before stitching.
    """
    if len(images) == 1:
        return images[0]

    target_height = max(img.height for img in images)

    resized = []
    for img in images:
        if img.height != target_height:
            scale = target_height / img.height
            new_w = int(img.width * scale)
            img = img.resize((new_w, target_height), Image.LANCZOS)
        resized.append(img)

    total_width = sum(img.width for img in resized) + gap * (len(resized) - 1)
    canvas = Image.new("RGB", (total_width, target_height), (255, 255, 255))

    x_offset = 0
    for img in resized:
        canvas.paste(img, (x_offset, 0))
        x_offset += img.width + gap

    return canvas

# ── Shared API call helper ─────────────────────────────────────────────────────

def _encode_image(img: Image.Image, max_long_edge: int = 4096, max_bytes: int = 4 * 1024 * 1024) -> tuple[str, int, int, int, int]:
    """Resize + JPEG-compress a PIL image and return (base64_str, width, height, quality, byte_len)."""
    send_img = img.copy()
    if max(send_img.size) > max_long_edge:
        send_img.thumbnail((max_long_edge, max_long_edge), Image.LANCZOS)

    jpeg_quality = 90
    while True:
        buffered = io.BytesIO()
        send_img.convert("RGB").save(buffered, format="JPEG", quality=jpeg_quality)
        img_bytes = buffered.getvalue()
        if len(img_bytes) <= max_bytes or jpeg_quality <= 30:
            break
        jpeg_quality -= 10

    return base64.b64encode(img_bytes).decode("utf-8"), send_img.size[0], send_img.size[1], jpeg_quality, len(img_bytes)

def _call_vision_api(img_b64: str, system_prompt: str, params: APIParams, user_text: str = "") -> Optional[str]:
    """Send one image to the vision API. Returns the content or None on failure."""
    payload = params.payload(
        system_prompt,
        [
            {"type": "text", "text": user_text},
            {"type": "image_url", "image_url": {"url": f"data:image/jpeg;base64,{img_b64}"}},
        ],
    )
    try:
        response = requests.post(params.api_url, json=payload, headers=params.headers(), timeout=params.timeout_seconds)
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"]
    except requests.exceptions.Timeout:
        print(f"[Vision Prompt] Request timed out after {params.timeout_seconds}s")
        return None
    except (ConnectionError, ConnectionResetError, ConnectionAbortedError) as e:
        raise  # Let the caller decide whether to retry sequentially
    except Exception as e:
        print(f"[Vision Prompt] API error: {e}")
        return None


def _call_text_api(system_prompt: str, user_text: str, params: APIParams) -> Optional[str]:
    """Text-only API call for the Merge Multicall merge step."""
    payload = params.payload(system_prompt, user_text)
    try:
        response = requests.post(params.api_url, json=payload, headers=params.headers(), timeout=params.timeout_seconds)
        response.raise_for_status()
        return response.json()["choices"][0]["message"]["content"]
    except requests.exceptions.Timeout:
        print(f"[Vision Prompt] Merge call timed out after {params.timeout_seconds}s")
        return None
    except (ConnectionError, ConnectionResetError, ConnectionAbortedError) as e:
        raise
    except Exception as e:
        print(f"[Vision Prompt] Merge API error: {e}")
        return None

class VisionPromptScript(scripts.Script):

    def title(self):
        return "Vision Prompt Injector"

    def show(self, is_img2img):
        return scripts.AlwaysVisible

    def ui(self, is_img2img):
        gr.HTML("""
            <style>
            .vp-params-box {
                border: 1px solid var(--block-border-color);
                border-radius: 8px;
                padding: 10px;
                margin-top: 8px;
                margin-bottom: 4px;
            }
            .vp-image-box {
                border: 1px solid var(--block-border-color);
                border-radius: 8px;
                padding: 4px;
                margin: 0px;
            }
            .bottom-align {
                display: flex !important;
                flex-direction: column !important;
                margin-top: 8px !important;
                vertical-align: top !important;
            }
            </style>
            """)
        with gr.Accordion("Vision Prompt", open=False):
            with gr.Row():
                enabled = gr.Checkbox(
                    label="Enable Vision Prompt",
                    value=False)

            with gr.Row():
                model_name = gr.Textbox(
                    label="Model",
                    value="gpt-4o-mini",
                    scale=2
                )

                api_url = gr.Textbox(
                    label="API URL",
                    value="http://localhost:8000/v1/chat/completions",
                    scale=3
                )
                api_key = gr.Textbox(
                    label="API Key",
                    value="",
                    placeholder="sk-... (leave blank for local endpoints)",
                    type="password",
                    scale=2
                )

            with gr.Accordion("Settings", open=False, elem_classes="vp-params-box"):
                with gr.Row():
                    response_style = gr.Radio(
                        label="Response Style", show_label=False,
                        choices=["strict", "balanced", "creative"],
                        value="balanced",
                        info="Sets the variability of the vLLM's output",
                        scale=4,
                        elem_classes="bottom-align"
                    )
                    enable_reasoning = gr.Checkbox(
                        label="Enable Reasoning", 
                        value=False,
                        info="For 'thinking' models only",
                        scale=1,
                        elem_classes="bottom-align"
                    )
                    skip_cache = gr.Checkbox(
                        label="Skip Cache",
                        value=False,
                        info="Always do a new API call",
                        scale=1,
                        elem_classes="bottom-align"
                    )
                    timeout_seconds = gr.Number(
                        label="Request Timeout", show_label=False,
                        value=30,
                        minimum=5,
                        maximum=600,
                        step=1,
                        info="Response Timeout",
                        scale=1,
                        elem_classes="bottom-align"
                    )

            tabs_data = []

            with gr.Tabs():
                for i in range(3):
                    with gr.Tab(f"Vision Input #{i+1}") as tab:
                        with gr.Row():
                            slot_enabled = gr.Checkbox(
                                label="Enable slot",
                                value=True,
                                scale=0,
                                min_width=120
                            )

                        # ── Multi-image mode selector ──────────────────────────
                        with gr.Row():
                            multi_image_mode = gr.Radio(
                                label="Multi-Image Mode", show_label=False,
                                choices=["Stitch", "Merge Multicall"],
                                value="Stitch",
                                info=("Multi-Image Modes: "
                                    "[Stitch] Fast and cheap. Combine images side-by-side in one call. "
                                    "[Merge] Better quality, but much slower. One call per image, then a final call merges results."
                                ),
                            )

                        gr.Markdown(
                            f"Upload up to **{IMAGES_PER_SLOT} images**"
                        )

                        image_inputs    = []

                        with gr.Row(elem_classes="vp-image-box"):
                            for j in range(IMAGES_PER_SLOT):
                                with gr.Column(min_width=120):
                                    img_input = gr.Image(
                                        type="pil",
                                        label=f"Image {j+1}",
                                        height=256,
                                    )

                                image_inputs.append(img_input)

                        # ── Preset / system prompt ─────────────────────────
                        gr.Markdown("### Prompt Preset")
                        with gr.Row(equal_height=True):
                            preset_dropdown = gr.Dropdown(
                                choices=list(SYSTEM_PROMPT_PRESETS.keys()),
                                value="Custom",
                                scale=3,
                                show_label=False
                            )
                            preset_name_input = gr.Textbox(
                                placeholder="Preset name...",
                                show_label=False,
                                scale=2,
                                max_lines=1
                            )

                            save_btn = gr.Button("💾", scale=0, min_width=40)
                            delete_btn = gr.Button("🗑️", scale=0, min_width=40)

                        system_prompt = gr.Textbox(
                            label="System Prompt",
                            value="Describe this image in detail for Stable Diffusion prompting."
                        )

                        def apply_preset(choice):
                            return SYSTEM_PROMPT_PRESETS.get(choice, ""), choice

                        preset_dropdown.change(
                            fn=apply_preset,
                            inputs=[preset_dropdown],
                            outputs=[system_prompt, preset_name_input]
                        )
                        save_btn.click(
                            fn=save_preset,
                            inputs=[preset_name_input, system_prompt],
                            outputs=[preset_dropdown, preset_name_input]
                        )
                        delete_btn.click(
                            fn=delete_preset,
                            inputs=[preset_dropdown],
                            outputs=[preset_dropdown, preset_name_input]
                        )

                        weight = gr.Slider(
                            label="Prompt Weight",
                            minimum=0.0,
                            maximum=2.0,
                            value=1.0,
                            step=0.05
                        )

                        # Pack
                        tabs_data.append(slot_enabled)
                        tabs_data.append(multi_image_mode)
                        tabs_data.extend(image_inputs)
                        tabs_data.extend([system_prompt, weight])

        return [
            enabled, api_url, model_name, api_key,
            response_style, enable_reasoning,
            timeout_seconds, skip_cache,
        ] + tabs_data

    def process(self, p, enabled, api_url, model_name, api_key, response_style, enable_reasoning, timeout_seconds, skip_cache, *args):
        if not enabled:
            return

        params = APIParams(
            model_name=model_name,
            api_url=api_url,
            api_key=api_key,
            response_style=response_style,
            enable_reasoning=enable_reasoning,
            timeout_seconds=timeout_seconds,
        )

        # ── Build slot work items ─────────────────────────────────────────
        slot_tasks = []
        for slot_idx in range(3):
            base = slot_idx * SLOT_STRIDE
            if not args[base + SLOT_ENABLED_OFF]:
                continue
            slot_tasks.append({
                "slot_idx":       slot_idx,
                "multi_mode":     args[base + MULTI_MODE_OFF],
                "images":         [args[base + IMG_OFF + j] for j in range(IMAGES_PER_SLOT)],
                "system_prompt":  args[base + SYSTEM_PROMPT_OFF],
                "weight":         args[base + WEIGHT_OFF],
            })

        # ── Run all enabled slots in parallel ─────────────────────────────
        def _run_slot(task):
            slot_idx = task["slot_idx"]
            try:
                result = self._process_slot(
                    p, slot_idx, task["multi_mode"], task["images"],
                    task["system_prompt"], task["weight"],
                    skip_cache, params,
                )
                return slot_idx, result, None
            except Exception as e:
                print(f"[Vision Prompt][Slot {slot_idx+1}] Failed: {e}")
                return slot_idx, None, e

        slot_results = [None] * 3
        with ThreadPoolExecutor(max_workers=min(len(slot_tasks), 3)) as executor:
            for slot_idx, result, error in executor.map(_run_slot, slot_tasks):
                if error is None:
                    slot_results[slot_idx] = result

        combined_prompts = [r for r in slot_results if r]
        if not combined_prompts:
            return

        final_injection = "\n\n".join(combined_prompts)
        print(f"[Vision Prompt] Final Injection:\n{final_injection}")

        p.prompt = f"{p.prompt}\n\n{final_injection}"

        if hasattr(p, "all_prompts") and p.all_prompts:
            p.all_prompts = [
                f"{prompt}\n\n{final_injection}" for prompt in p.all_prompts
            ]

    def _process_slot(self, p, slot_idx, multi_image_mode, slot_images, system_prompt, weight, skip_cache, params: APIParams):
        def _handle_line_refs(text: str, prefix: str, lines: list) -> str:
            """Replace {prefix+N} and {prompt-N} with line slices from lines."""
            pattern = re.escape(prefix) + r"([+-]\d+)"
            for match in re.finditer(pattern, text):
                num = int(match.group(1))
                if num >= 0:
                    trimmed = "\n".join(lines[num:]) if num < len(lines) else ""
                else:
                    num = abs(num)
                    trimmed = "\n".join(lines[:-num]) if num < len(lines) else ""
                text = text.replace(match.group(0), trimmed, 1)
            return text

        def _resolve_placeholders(text: str, prompt: str, neg: str) -> str:
            """Resolve prompt and negative prompt placeholders in text."""
            lines_pos = prompt.split("\n")
            lines_neg = neg.split("\n") if neg else []

            replacements = [
                ("{prompt", lines_pos),
                ("{negative_prompt", lines_neg),
            ]
            for prefix, lines in replacements:
                text = _handle_line_refs(text, prefix, lines)

            text = text.replace("{prompt}", prompt)
            text = text.replace("{negative_prompt}", neg)
            return text

        neg = p.negative_prompt if hasattr(p, "negative_prompt") else ""
        system_prompt = _resolve_placeholders(system_prompt, p.prompt, neg)
        if not system_prompt.strip():
            return None

        valid_images = [img for img in slot_images if img is not None]
        if not valid_images:
            return None

        if multi_image_mode == "Stitch" or len(valid_images) == 1:
            vision_output = self._run_stitch(
                valid_images, slot_idx, system_prompt,
                skip_cache, params,
            )
        else:
            vision_output = self._run_merge_multicall(
                valid_images, slot_idx, system_prompt,
                skip_cache, params,
            )

        if not vision_output:
            return None

        vision_output = vision_output.strip().replace("\n\n", "\n").replace(":", "\\:").replace("(", "\\(").replace(")", "\\)").replace("[", "\\[").replace("]", "\\]")
        weighted_prompt = f"({vision_output}:{weight})"

        print(f"[Vision Prompt][Slot {slot_idx+1}] {weighted_prompt}")
        return weighted_prompt

    # ── Strategy: Stitch ──────────────────────────────────────────────────────

    def _run_stitch(self, valid_images, slot_idx, system_prompt, skip_cache, params: APIParams):
        if len(valid_images) == 1:
            composed     = valid_images[0]
            stitch_desc  = "1 image"
        else:
            composed     = stitch_images_horizontal(valid_images)
            stitch_desc  = f"{len(valid_images)} images stitched"

        print(f"\n[Vision Prompt][Slot {slot_idx+1}] Stitch — {stitch_desc}")

        img_b64, w, h, quality, nbytes = _encode_image(composed)
        print(f"[Vision Prompt][Slot {slot_idx+1}] Sending {w}×{h}px JPEG @ quality={quality} ({nbytes//1024} KB)")

        cache_key = self._cache_key_images(
            valid_images, system_prompt, params, suffix="stitch"
        )
        return self._cached_call(
            cache_key, slot_idx, skip_cache,
            lambda: _call_vision_api(img_b64, system_prompt, params)
        )

    # ── Strategy: Merge Multicall ─────────────────────────────────────────────

    def _run_merge_multicall(self, valid_images, slot_idx, system_prompt, skip_cache, params: APIParams):
        """
        One API call per image (no schema constraints), followed by a second text-only
        call that merges the individual descriptions into the schema defined by the
        original system prompt.

        Step 1 is parallelized with ThreadPoolExecutor since each image call is independent.
        """
        print(f"\n[Vision Prompt][Slot {slot_idx+1}] Merge Multicall — {len(valid_images)} image(s)")

        # ── Step 1: describe each image independently (parallel) ──────────
        def _process_one(args_tuple):
            j, img = args_tuple
            try:
                img_b64, w, h, quality, nbytes = _encode_image(img)
                cache_key = self._cache_key_images(
                    [img], system_prompt, params, suffix=f"merge_sub_{j}"
                )
                output = self._cached_call(
                    cache_key, slot_idx, skip_cache,
                    lambda b64=img_b64: _call_vision_api(b64, system_prompt, params)
                )
                log_msg = f"[Vision Prompt][Slot {slot_idx+1}] Image {j+1}: {w}×{h}px JPEG @ quality={quality} ({nbytes//1024} KB)"
                return (j, output.strip() if output else None, cache_key, log_msg)
            except Exception as e:
                print(f"[Vision Prompt][Slot {slot_idx+1}] Image {j+1} failed: {e}")
                return (j, None, None, None)

        with ThreadPoolExecutor(max_workers=min(len(valid_images), 4)) as executor:
            results = list(executor.map(_process_one, enumerate(valid_images)))

        # Print logs after thread execution to avoid interleaving
        for _, _, _, log_msg in results:
            if log_msg:
                print(log_msg)

        # Preserve original image order
        results.sort(key=lambda x: x[0])
        individual_outputs = [out for _, out, _, _ in results if out]
        individual_cache_keys = [ck for _, _, ck, _ in results if ck]

        if not individual_outputs:
            return None

        # If there is only one result there is nothing to merge
        if len(individual_outputs) == 1:
            return individual_outputs[0]

        # ── Step 2: merge via a text-only call ────────────────────────────
        descriptions_block = "\n".join(
            f"Input #{j+1}: {desc}" for j, desc in enumerate(individual_outputs)
        )

        merge_system = MERGE_SYSTEM_TEMPLATE.format(system_prompt=system_prompt)
        merge_user = MERGE_USER_TEMPLATE.format(
            count=len(individual_outputs),
            descriptions_block=descriptions_block
        )

        merge_cache_key = self._cache_key_merge(individual_cache_keys, merge_system, merge_user)

        merged = self._cached_call(
            merge_cache_key, slot_idx, skip_cache,
            lambda: _call_text_api(merge_system, merge_user, params)
        )

        return merged

    # ── Cache helpers ─────────────────────────────────────────────────────────

    @staticmethod
    def _cache_key_images(images, system_prompt, params: APIParams, suffix=""):
        hash_parts = b"".join(VisionPromptScript._pil_to_bytes(img) for img in images)
        param_str = f"{params.response_style}|{params.enable_reasoning}"
        raw = (
            hash_parts
            + system_prompt.encode("utf-8")
            + params.model_name.encode("utf-8")
            + params.api_url.encode("utf-8")
            + param_str.encode("utf-8")
            + suffix.encode("utf-8")
        )
        return hashlib.sha256(raw).hexdigest()

    @staticmethod
    def _cache_key_merge(individual_cache_keys: list[str], merge_system: str, merge_user: str) -> str:
        """Generate a cache key for the merge step based on sub-keys and merge prompts."""
        merge_hash_input = (
            "".join(individual_cache_keys)
            + merge_system
            + merge_user
        ).encode("utf-8")
        return hashlib.sha256(merge_hash_input).hexdigest()

    def _cached_call(self, cache_key, slot_idx, skip_cache, call_fn) -> Optional[str]:
        """
        Look up cache_key in the slot cache. On a miss, call call_fn()
        and store the result. Returns the cached or freshly-fetched string.
        Thread-safe via a per-slot lock.
        """
        slot_cache: OrderedDict = VISION_CACHE[slot_idx]
        lock = VISION_CACHE_LOCKS[slot_idx]

        with lock:
            if not skip_cache and cache_key in slot_cache:
                # Move to end (most recently used) for LRU behavior
                result = slot_cache.pop(cache_key)
                slot_cache[cache_key] = result
                print(f"[Vision Prompt][Slot {slot_idx+1}] Cache HIT")
                return result
            print(f"[Vision Prompt][Slot {slot_idx+1}] Cache MISS — calling API")

        result = call_fn()

        with lock:
            if result and not skip_cache:
                if len(slot_cache) >= CACHE_SIZE:
                    # Pop the oldest item (first in OrderedDict)
                    slot_cache.popitem(last=False)
                slot_cache[cache_key] = result

        return result

    # ── Misc helpers ──────────────────────────────────────────────────────────

    @staticmethod
    def _pil_to_bytes(img: Image.Image) -> bytes:
        buf = io.BytesIO()
        img.save(buf, format="PNG")
        return buf.getvalue()